- name: Include OS specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "family_{{ ansible_os_family }}.yml"
    - family_default.yml

- name: Include service manager specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "service_mgr_{{ ansible_service_mgr | mandatory }}.yml"
    - service_mgr_default.yml

- debug:
    msg:
      - "_apache_service_start_command"
      - "{{ _apache_service_start_command }}"
      - "_apache_service_stop_command"
      - "{{ _apache_service_stop_command }}"
      - "_apache_service_status_command"
      - "{{ _apache_service_status_command }}"
      - "_apache_service_name"
      - "{{ _apache_service_name }}"

- include_tasks: start_apache.yml
  when: apache_service_state == 'started'

- include_tasks: stop_apache.yml
  when: apache_service_state == 'stopped'

- include_tasks: restart_apache.yml
  when: apache_service_state == 'restarted'
