- name: Start Apache (escalated).
  service:
    name: "{{ _apache_service_name }}"
    state: started
  register: apache_service_start_result
  when: not apache_service_restricted_mode

- name: Start Apache (restricted).
  block:
    - name: Retrieve apache status (restricted).
      raw: "{{ _apache_service_status_command }}"
      changed_when: false
      register: _apache_status_result_1
      failed_when:
        - _apache_status_result_1.rc != 0
        - _apache_status_result_1.rc != 3

    - name: Start Apache (restricted).
      raw: "{{ _apache_service_start_command }}"
      when: _apache_status_result_1.rc != 0
      register: _apache_start_result

    - name: Ensure that Apache is started (restricted).
      raw: "{{ _apache_service_status_command }}"
      changed_when: false
      register: _apache_status_result_2
      failed_when:
        - _apache_status_result_2.rc != 0
      when: _apache_start_result.changed

  when: apache_service_restricted_mode
