- name: Stop Apache (escalated).
  service:
    name: "{{ apache_service_name }}"
    state: stopped
  register: apache_service_stop_result
  when: not apache_service_restricted_mode

- name: Stop Apache (restricted).
  block:
    - name: Retrieve Apache status (restricted).
      raw: "{{ _apache_service_status_command }}"
      changed_when: false
      failed_when:
        - _apache_status_result.rc != 0
        - _apache_status_result.rc != 3
      register: _apache_status_result

    - name: Stop Apache (restricted).
      raw: "{{ _apache_service_stop_command }}"
      when: _apache_status_result.rc == 0

  when: apache_service_restricted_mode
